[tool.poetry]
name = "nextcloudtalkbot"
version = "0.0.46"
description = "Python3 library for creating a Nextcloud Talk bot."
authors = ["Massoud Ahmed <okko@okxo.de>"]
license = "GNU General Public License v3 (GPLv3)"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.29.0"
attrs = "^23.1.0"
caldav = "^1.2.1"
cryptography = "^40.0.2"
python-dateutil = "^2.8.2"
icalendar = "^5.0.5"
requests-cache = "^1.0.1"
spacy = "^3.5.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
